server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pku
    username: pku
    password: pku
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/pku
          jwk-set-uri: http://localhost:8180/realms/pku/protocol/openid-connect/certs
